version: "3.9"

services:
  cockroachdb:
    container_name: cockroachdb
    image: cockroachdb/cockroach:v22.2.8
    command:
      - start-single-node
      - --insecure
      - --listen-addr=localhost:26257
      - --http-addr=0.0.0.0:8080
      - --sql-addr=cockroachdb:26257
      - --accept-sql-without-tls
    environment:
      COCKROACH_ALLOW_INTERNET_ACCESS: "true"
    ports:
      - "26258:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health?ready=1 || exit 1"]
      interval: 15s
      timeout: 45s
      retries: 20
      start_period: 30s
    networks:
      betterdiscord:
        aliases:
          - cockroachdb
    restart: unless-stopped

  backend:
    build:
      context: ./backend/chat_app
    environment:
      DATABASE_URL: "postgresql://root@cockroachdb:26257/chat_app_dev?sslmode=disable"
      GOOGLE_CLIENT_ID: "58516048770-lqsao96iscal7fb850pgmre3cmhpvm6q.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "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"
    ports:
      - "4000:4000"
    volumes:
      - ./backend/chat_app/secrets:/run/secrets:ro
    networks:
      - betterdiscord
    depends_on:
      cockroachdb:
        condition: service_healthy
    restart: unless-stopped

  coturn:
    container_name: betterdiscord-coturn
    image: instrumentisto/coturn:4.5.2
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
      - "50000-51000:50000-51000/udp"
    volumes:
      - ./backend/chat_app/secrets/turnserver.conf:/etc/coturn/turnserver.conf:ro
    command: >
      turnserver -c /etc/coturn/turnserver.conf
      --log-file=stdout
      --no-tls
      --no-dtls
      --cli-password=123456
    networks:
      betterdiscord:
        aliases:
          - coturn
    restart: unless-stopped

  mediasoup:
    container_name: mediasoup-server
    build:
      context: ./mediasoup-server
    ports:
      - "3001:3001"
      - "40000-40100:40000-40100/udp"
    networks:
      - betterdiscord
    restart: unless-stopped
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    command: server /data --console-address ":9001"
    ports:
      - "9002:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    volumes:
      - minio-data:/data
    networks:
      - betterdiscord
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - betterdiscord
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  cockroach-data:
  minio-data:

networks:
  betterdiscord:
    driver: bridge
