FROM elixir:1.15-alpine

RUN apk add --no-cache build-base git nodejs npm postgresql-client inotify-tools

WORKDIR /app

RUN mix local.hex --force && mix local.rebar --force

COPY mix.exs mix.lock ./
RUN mix deps.get
RUN mix deps.compile

# Copy the certs folder from root into /app/certs inside the container
COPY ../certs ./certs

COPY . .

RUN mix compile

EXPOSE 4000

CMD ["mix", "phx.server"]
