version: "3.9"

services:
  cockroachdb:
    image: cockroachdb/cockroach
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8081:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    networks:
      - backend

  coturn:
    image: instrumentisto/coturn
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
    volumes:
      - ./secrets:/run/secrets:ro
    environment:
      - REALM=localhost
    command:
      - turnserver
      - --lt-cred-mech
      - --log-file=stdout
      - --realm=localhost
      - --user=$(cat /run/secrets/turn_username.txt):$(cat /run/secrets/turn_password.txt)
      - --no-cli
      - --no-tls
      - --no-dtls
      - --allow-loopback-peers
      - --allowed-peer-ip=0.0.0.0-255.255.255.255
    restart: unless-stopped
    networks:
      - backend

  janus:
    image: canyan/janus-gateway
    ports:
      - "8088:8088"
      - "8188:8188"
    volumes:
      - janus-config:/usr/local/etc/janus
    environment:
      - JANUS_LOG_LEVEL=4
      - JANUS_NAT_STUN_SERVER=coturn
      - JANUS_NAT_STUN_PORT=3478
    depends_on:
      - coturn
    networks:
      - backend

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data
    volumes:
      - minio-data:/data
    restart: unless-stopped
    networks:
      - backend

  app:
    build: .
    depends_on:
      - cockroachdb
      - janus
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://root@cockroachdb:26257/chat_app_dev?sslmode=disable
      - JANUS_URL=ws://janus:8188
    networks:
      - backend

volumes:
  cockroach-data:
  janus-config:
  minio-data:

networks:
  backend:
    driver: bridge
