version: "3.8"

services:
  cockroachdb:
    image: cockroachdb/cockroach:v23.1.11
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8081:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data

  app:
    build: .
    depends_on:
      - cockroachdb
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://root@cockroachdb:26257/chat_app_dev?sslmode=disable

volumes:
  cockroach-data:
